[user]
name = "Patrick Dewey"
email = "57921252+ptdewey@users.noreply.github.com"

# TODO: maybe add extra scoping around hostnames
[[--scope]]
--when.repositories = ["~/workspace"]
[--scope.user]
name = "Patrick Dewey"
email = ""

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
# private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
private-commits = "description(glob:'private:*')"

[ui]
# paginate = "never"
default-command = ["log", "--no-pager", "--limit=20"]
